/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetDotjsRouteImport } from './routes/widget[.]js'
import { Route as WidgetTestRouteImport } from './routes/widget-test'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWidgetConfigRouteImport } from './routes/api.widget-config'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiIngestMenuRouteImport } from './routes/api.ingest-menu'
import { Route as ApiConciergeRouteImport } from './routes/api.concierge'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiBillingPortalRouteImport } from './routes/api.billing-portal'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const WidgetDotjsRoute = WidgetDotjsRouteImport.update({
  id: '/widget.js',
  path: '/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetTestRoute = WidgetTestRouteImport.update({
  id: '/widget-test',
  path: '/widget-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetConfigRoute = ApiWidgetConfigRouteImport.update({
  id: '/api/widget-config',
  path: '/api/widget-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestMenuRoute = ApiIngestMenuRouteImport.update({
  id: '/api/ingest-menu',
  path: '/api/ingest-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing-portal',
  path: '/api/billing-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/widget-test': typeof WidgetTestRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/ingest-menu': typeof ApiIngestMenuRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/widget-config': typeof ApiWidgetConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/widget-test': typeof WidgetTestRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/ingest-menu': typeof ApiIngestMenuRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/widget-config': typeof ApiWidgetConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/widget-test': typeof WidgetTestRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/billing-portal': typeof ApiBillingPortalRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/ingest-menu': typeof ApiIngestMenuRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/widget-config': typeof ApiWidgetConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/widget-test'
    | '/widget.js'
    | '/dashboard'
    | '/onboarding'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/concierge'
    | '/api/ingest-menu'
    | '/api/stripe-webhook'
    | '/api/widget-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/widget-test'
    | '/widget.js'
    | '/dashboard'
    | '/onboarding'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/concierge'
    | '/api/ingest-menu'
    | '/api/stripe-webhook'
    | '/api/widget-config'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/widget-test'
    | '/widget.js'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/api/billing-portal'
    | '/api/checkout'
    | '/api/concierge'
    | '/api/ingest-menu'
    | '/api/stripe-webhook'
    | '/api/widget-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WidgetTestRoute: typeof WidgetTestRoute
  WidgetDotjsRoute: typeof WidgetDotjsRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  ApiIngestMenuRoute: typeof ApiIngestMenuRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWidgetConfigRoute: typeof ApiWidgetConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget.js': {
      id: '/widget.js'
      path: '/widget.js'
      fullPath: '/widget.js'
      preLoaderRoute: typeof WidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-test': {
      id: '/widget-test'
      path: '/widget-test'
      fullPath: '/widget-test'
      preLoaderRoute: typeof WidgetTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget-config': {
      id: '/api/widget-config'
      path: '/api/widget-config'
      fullPath: '/api/widget-config'
      preLoaderRoute: typeof ApiWidgetConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest-menu': {
      id: '/api/ingest-menu'
      path: '/api/ingest-menu'
      fullPath: '/api/ingest-menu'
      preLoaderRoute: typeof ApiIngestMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-portal': {
      id: '/api/billing-portal'
      path: '/api/billing-portal'
      fullPath: '/api/billing-portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WidgetTestRoute: WidgetTestRoute,
  WidgetDotjsRoute: WidgetDotjsRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  ApiIngestMenuRoute: ApiIngestMenuRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWidgetConfigRoute: ApiWidgetConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
